### ISSUE TITLE
Create new project, riak-erlang-client-common

### ISSUE THREAD

**Issue by varnerac** [basho/riak-erlang-http-client#35]
riak-erlang-http-client currently depends on riak-erlang-client. The two projects both depend on common Erlang Riak client functionality, but should not see each other. I think the following functionality can be split out into a new project, riak-erlang-client-common.

1) https://github.com/basho/riak-erlang-client/blob/master/src/riakc_obj.erl
2) https://github.com/basho/riak-erlang-client/blob/master/include/riakc.hrl
3) <code>-spec</code>s for common exported functions. This would require a common client type <code>-type client :: rhc() | pid()</code>
4) Integration tests. I think that integration tests should be split out from the unit tests. This should make it possible to run unit tests in the Travis CI build and run integration tests outside of Travis.

The functionality differs between the two client libraries. As an example, riak-erlang-http-client lacks the protobuf client's <code>get/5</code>, a get with a <code>Timeout</code> option. The testing gap between the two clients is dramatic.

I'd like to see if the maintainers/reviewers would support this sort of refactoring before I tackle it.

**Comment by bsparrow435** [comment]
Quick update here. This client is still officially supported and we appreciate any and all community reported issues, suggestions, and PR's. Apologies that many issues have languished for a while but we're working on cleaning that up now.
