### ISSUE TITLE
Please create file src/riakhttpc.app.src with contents for ebin/riakhttpc.app 

### ISSUE THREAD

**Issue by edwardt** [basho/riak-erlang-http-client#38]
Noticed that under ebin, there is riakhttpc.app but under src there is not such file.

Since rebar compile generate the .app, so unsure why not let compile process to generate from the .app.src file under src. 

This is especially important when companies are implementing automated build with checks/validation rules in place. Would be nice if this project is kept as uniform as other projects.

Tried generated riakhttpc.app.src with the same content locally and it seems to work no problem.

Thanks

**Comment by lukebakken** [comment]
Fixed by eb4ffe18d940b1171f0a8df9d5cbbd7426430d51
